apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: webhomework
    image: v0lshebnick/web-server:latest
    volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
  - name: initcontainerforweb
    image: busybox:1.33.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app

  volumes:
    - name: app
      emptyDir: {}